name: Download Signal Dependencies

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download binance authenticator
        run: |
          mkdir -p deps
          curl -L "https://download.binance.com/authenticator/binance-authenticator.apk" -o deps/aa.apk
          ls -lh deps/

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: signal-deps
          path: deps/
          retention-days: 7

